variables:
  # Timezone will be used both for system and php date.timezone php.ini value
  TIMEZONE: "Europe/Paris"

stages:
  - install
  - check
  - test

composer:
  stage: install
  image: composer:1.6.2
  script:
    - mkdir bin var
    - composer install --prefer-dist
  tags:
    - test
  cache:
    paths:
      - vendor/
  artifacts:
    expire_in: 1 hr
    paths:
      - vendor/
      - var/
      - bin/

messDetector:
  stage: check
  tags:
    - test
  dependencies:
    - composer
  image: php:7.2-cli-alpine3.7
  script:
    - php -f vendor/bin/phpmd ./ text ./build/config/phpmd.xml --exclude vendor/,bin/,build/

checkStyle:
  stage: check
  tags:
    - test
  dependencies:
    - composer
  image: php:7.2-cli-alpine3.7
  script:
    - php vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml lib
    - php vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml specs

atoum:
  stage: test
  tags:
    - test
  dependencies:
    - composer
  image: php:7.2-cli-alpine3.7
  script:
    - php -f vendor/bin/atoum -- -ft
