language: php
php:
  - 7.1
before_script:
  - composer install
script:
  - vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml lib
  - vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml specs
  - php specs/units/runner.php
