language: php
php:
  - 7.2
before_script:
  - composer install
script:
  - vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml lib
  - vendor/bin/phpcs --encoding=UTF-8 --standard=check-style.xml specs
  - vendor/bin/phpmd ./lib text ./phpmd.xml
  - php specs/units/runner.php
