version: '3'

services:
    php-cli:
        image: php:7.2.4-cli-alpine3.7
        working_dir: /src
        volumes:
            - .:/src

    composer:
        image: composer:1.7.3
        working_dir: /src
        volumes:
            - .:/src
        environment:
            - COMPOSER_CACHE_DIR=/.composer
            - COMPOSER_ALLOW_SUPERUSER=1
